modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="pury_music"
version="1.0.4"
displayName="Pury Music"
credits="Created using MCreator"
displayURL="https://insomnia-game.com"
authors="GideonWhite1029"
description='''
Music by Pury World
'''

[[dependencies.pury_music]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




